In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-01-13 18:09:16.847630: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-13 18:09:16.918231: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-13 18:09:17.228759: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-13 18:09:17.228893: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-13 18:09:17.271625: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2765, 3980, 1590, 9134],
 [2765, 3980, 1590, 9954],
 [2765, 8257, 1590, 4138],
 [7257, 3468, 1655, 6574, 5701],
 [7257, 3468, 1655, 6574, 2518],
 [4102, 2765, 4093, 1590, 5812],
 [3335, 2491, 6345, 6574]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
# since all the sentence are not of equal length we use pad_sequence 
# to keep length equal through out
print(embedded_docs)

[[   0    0    0    0 2765 3980 1590 9134]
 [   0    0    0    0 2765 3980 1590 9954]
 [   0    0    0    0 2765 8257 1590 4138]
 [   0    0    0 7257 3468 1655 6574 5701]
 [   0    0    0 7257 3468 1655 6574 2518]
 [   0    0    0 4102 2765 4093 1590 5812]
 [   0    0    0    0 3335 2491 6345 6574]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)
# every word is represented in 10 dimensions

1/1 [==============================] - 0s 50ms/step


array([[[ 1.65281035e-02,  4.63016294e-02,  3.04995812e-02,
          4.78094853e-02,  3.49697582e-02, -6.06484339e-03,
          1.05619803e-02,  2.98811309e-02,  8.55418295e-03,
          3.43756340e-02],
        [ 1.65281035e-02,  4.63016294e-02,  3.04995812e-02,
          4.78094853e-02,  3.49697582e-02, -6.06484339e-03,
          1.05619803e-02,  2.98811309e-02,  8.55418295e-03,
          3.43756340e-02],
        [ 1.65281035e-02,  4.63016294e-02,  3.04995812e-02,
          4.78094853e-02,  3.49697582e-02, -6.06484339e-03,
          1.05619803e-02,  2.98811309e-02,  8.55418295e-03,
          3.43756340e-02],
        [ 1.65281035e-02,  4.63016294e-02,  3.04995812e-02,
          4.78094853e-02,  3.49697582e-02, -6.06484339e-03,
          1.05619803e-02,  2.98811309e-02,  8.55418295e-03,
          3.43756340e-02],
        [-2.94303894e-02,  8.19706917e-03,  2.74321921e-02,
          1.25315078e-02, -4.13591750e-02, -1.10372305e-02,
          4.56802957e-02, -4.53519486e-02, -1.327507

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 2765, 3980, 1590, 9134], dtype=int32)

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 79ms/step


array([[ 0.0165281 ,  0.04630163,  0.03049958,  0.04780949,  0.03496976,
        -0.00606484,  0.01056198,  0.02988113,  0.00855418,  0.03437563],
       [ 0.0165281 ,  0.04630163,  0.03049958,  0.04780949,  0.03496976,
        -0.00606484,  0.01056198,  0.02988113,  0.00855418,  0.03437563],
       [ 0.0165281 ,  0.04630163,  0.03049958,  0.04780949,  0.03496976,
        -0.00606484,  0.01056198,  0.02988113,  0.00855418,  0.03437563],
       [ 0.0165281 ,  0.04630163,  0.03049958,  0.04780949,  0.03496976,
        -0.00606484,  0.01056198,  0.02988113,  0.00855418,  0.03437563],
       [-0.02943039,  0.00819707,  0.02743219,  0.01253151, -0.04135917,
        -0.01103723,  0.0456803 , -0.04535195, -0.01327508, -0.00888913],
       [-0.00198454, -0.03696653,  0.02865935, -0.0466635 ,  0.03985076,
        -0.00214375, -0.00838554,  0.03361816, -0.03021367, -0.02300494],
       [-0.03656058, -0.02170037,  0.03590426, -0.03248353,  0.00331693,
         0.03720142, -0.02494439, -0.0273597 